In [1]:
import numpy as np                                      # Importa numpy para trabajar con matrices
import matplotlib.pyplot as plt                         # Importa matplotlib para graficar si se desea

def givens_rotation(a, b):                              # Calcula los parametros c y s de una rotacion de Givens
    
    if b == 0:                                          # Si b ya es cero, no se necesita rotacion
        c = 1.0                                         # Coseno igual a 1
        s = 0.0                                         # Seno igual a 0
    
    else:                                               # Si b no es cero, se calcula la rotacion
        r = np.sqrt(a**2 + b**2)                        # Calcula r = sqrt(a^2+b^2)
        c = a / r                                       # Calcula el coseno de la rotacion
        s = b / r                                       # Calcula el seno de la rotacion
    
    return c, s                                         # Devuelve los parametros de Givens


def qr_givens(A):                                       # Funcion que calcula la factorizacion QR por Givens
    
    A = A.astype(float)                                 # Convierte la matriz a tipo flotante
    m, n = A.shape                                      # Obtiene numero de filas y columnas
    
    Q = np.eye(m)                                       # Inicializa Q como la matriz identidad
    R = A.copy()                                        # Inicializa R como una copia de A
    
    for k in range(min(m - 1, n)):                      # Recorre las columnas donde se eliminaran entradas
        
        for l in range(k + 1, m):                       # Recorre las filas debajo del pivote
            
            a = R[k, k]                                 # Elemento pivote
            b = R[l, k]                                 # Elemento que se desea anular
            
            c, s = givens_rotation(a, b)                # Calcula coseno y seno de Givens
            
            G = np.eye(m)                               # Construye una matriz identidad de tamano m
            
            G[k, k] = c                                 # Coloca c en la posicion (k,k)
            G[l, l] = c                                 # Coloca c en la posicion (l,l)
            G[k, l] = s                                 # Coloca s en la posicion (k,l)
            G[l, k] = -s                                # Coloca -s en la posicion (l,k)
            
            R = G @ R                                   # Aplica la rotacion a R para anular R[l,k]
            Q = Q @ G.T                                 # Acumula Q usando la transpuesta de G
    
    return Q, R                                         # Devuelve Q y R

In [2]:
A = np.array([[6, 5, 0],
              [5, 1, 4],
              [0, 4, 3]], dtype=float)                  # Define una matriz de prueba

Q, R = qr_givens(A)                                     # Calcula QR por Givens

print("Matriz A:")
print(A)

print("\nMatriz Q:")
print(Q)

print("\nMatriz R:")
print(R)

print("\nProducto Q @ R:")
print(Q @ R)

print("\nError ||A - QR||:")
print(np.linalg.norm(A - Q @ R))

print("\nError de ortogonalidad ||Q^T Q - I||:")
print(np.linalg.norm(Q.T @ Q - np.eye(Q.shape[0])))

Matriz A:
[[6. 5. 0.]
 [5. 1. 4.]
 [0. 4. 3.]]

Matriz Q:
[[ 0.76822128  0.33265418  0.54697099]
 [ 0.6401844  -0.39918502 -0.65636519]
 [ 0.          0.854396   -0.51962244]]

Matriz R:
[[ 7.81024968e+00  4.48129080e+00  2.56073760e+00]
 [ 2.30758718e-16  4.68166987e+00  9.66447932e-01]
 [ 3.79428043e-16  0.00000000e+00 -4.18432806e+00]]

Producto Q @ R:
[[ 6.00000000e+00  5.00000000e+00 -1.32410673e-17]
 [ 5.00000000e+00  1.00000000e+00  4.00000000e+00]
 [ 7.14075973e-33  4.00000000e+00  3.00000000e+00]]

Error ||A - QR||:
1.489579343908189e-15

Error de ortogonalidad ||Q^T Q - I||:
3.399575360592919e-16
