In [2]:
import numpy as np                                      # Libreria para trabajar con matrices

def gepc(A):                                            # GEPC = eliminacion gaussiana con pivotaje completo
    A = A.astype(float).copy()                          # Copia de A en formato decimal
    n = A.shape[0]                                      # Numero de filas/columnas
    P = np.eye(n)                                       # Matriz de permutacion de filas
    Q = np.eye(n)                                       # Matriz de permutacion de columnas
    L = np.eye(n)                                       # Matriz triangular inferior
    alfa = np.max(np.abs(A))                            # Mayor elemento inicial de A
    maximos = [alfa]                                    # Guarda maximos para el factor de crecimiento

    print("Matriz inicial A:")
    print(A)

    for k in range(n - 1):                              # Recorre las columnas pivote
        sub = np.abs(A[k:n, k:n])                       # Submatriz donde se busca el pivote
        pos = np.argmax(sub)                            # Posicion del mayor valor absoluto
        r, s = np.unravel_index(pos, sub.shape)         # Convierte la posicion a fila y columna
        r = r + k                                       # Fila real del pivote
        s = s + k                                       # Columna real del pivote

        print(f"\nPaso k = {k+1}")                      # Imprime el paso actual
        print(f"Pivote = {A[r,s]} en fila {r+1}, columna {s+1}")

        if r != k:                                      # Si el pivote no esta en la fila k
            A[[k, r], :] = A[[r, k], :]                 # Intercambia filas en A
            P[[k, r], :] = P[[r, k], :]                 # Intercambia filas en P
            L[[k, r], :k] = L[[r, k], :k]               # Ajusta multiplicadores previos en L

        if s != k:                                      # Si el pivote no esta en la columna k
            A[:, [k, s]] = A[:, [s, k]]                 # Intercambia columnas en A
            Q[:, [k, s]] = Q[:, [s, k]]                 # Intercambia columnas en Q

        for i in range(k + 1, n):                       # Filas debajo del pivote
            m = -A[i, k] / A[k, k]                      # Multiplicador segun la teoria m_ik = -a_ik/a_kk
            L[i, k] = -m                                # En L se guarda l_ik = a_ik/a_kk
            A[i, k] = 0                                 # Anula la entrada debajo del pivote
            A[i, k+1:n] = A[i, k+1:n] + m*A[k, k+1:n]   # Actualiza la fila i

        maximos.append(np.max(np.abs(A)))               # Guarda maximo despues del paso
        print("Matriz despues de eliminar:")
        print(A)

    U = A                                               # La matriz final es triangular superior
    rho = max(maximos) / alfa                           # Factor de crecimiento

    return P, L, U, Q, rho                              # Devuelve P, L, U, Q y factor de crecimiento


A =#COLOCAR LA MATRIZ DE WILKINSON DE n=5

P, L, U, Q, rho = gepc(A)                               # Ejecuta el algoritmo

print("\nMatriz P:")
print(P)

print("\nMatriz L:")
print(L)

print("\nMatriz U:")
print(U)

print("\nMatriz Q:")
print(Q)

print("\nVerificacion P A Q:")
print(P @ A @ Q)

print("\nVerificacion L U:")
print(L @ U)

print("\nFactor de crecimiento rho:")
print(rho)

Matriz inicial A:
[[ 1.  0.  0.  0.  1.]
 [-1.  1.  0.  0.  1.]
 [-1. -1.  1.  0.  1.]
 [-1. -1. -1.  1.  1.]
 [-1. -1. -1. -1.  1.]]

Paso k = 1
Pivote = 1.0 en fila 1, columna 1
Matriz despues de eliminar:
[[ 1.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  2.]
 [ 0. -1.  1.  0.  2.]
 [ 0. -1. -1.  1.  2.]
 [ 0. -1. -1. -1.  2.]]

Paso k = 2
Pivote = 2.0 en fila 2, columna 5
Matriz despues de eliminar:
[[ 1.  1.  0.  0.  0.]
 [ 0.  2.  0.  0.  1.]
 [ 0.  0.  1.  0. -2.]
 [ 0.  0. -1.  1. -2.]
 [ 0.  0. -1. -1. -2.]]

Paso k = 3
Pivote = -2.0 en fila 3, columna 5
Matriz despues de eliminar:
[[ 1.  1.  0.  0.  0.]
 [ 0.  2.  1.  0.  0.]
 [ 0.  0. -2.  0.  1.]
 [ 0.  0.  0.  1. -2.]
 [ 0.  0.  0. -1. -2.]]

Paso k = 4
Pivote = -2.0 en fila 4, columna 5
Matriz despues de eliminar:
[[ 1.  1.  0.  0.  0.]
 [ 0.  2.  1.  0.  0.]
 [ 0.  0. -2.  1.  0.]
 [ 0.  0.  0. -2.  1.]
 [ 0.  0.  0.  0. -2.]]

Matriz P:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

M