Nombre: Azucena Caicedo

## 📚 Temas abordados Práctica 1
1. **Matrices en Python**
   - Definición con listas y con NumPy  
   - Suma de matrices  
   - Transpuesta  
   - Matriz identidad  
   - Inversa  

2. **Vectores en Python**
   - Definición  
   - Operaciones básicas
   - normas de vectores: 1, 3 e infinito.  


In [1]:
print("Hola, Mundo")

Hola, Mundo


In [2]:
print(2+3)

5


In [3]:
print("2+3=",2+3)

2+3= 5


Creando una función llamada **hello**

In [4]:
def hello():                                 #Definiendo una nueva función llamada hello
    print("Hello")
    print("Computers are fun!")

Llamando a la función **hello**

In [5]:
hello()

Hello
Computers are fun!


¿Ves lo que hace esta función? Imprime dos oraciones.

In [6]:
def greet(person):
    print("Hello", person)
    print("How are you?")

Personalizando nuestro saludo

In [7]:
greet("Sarahi")

Hello Sarahi
How are you?


In [8]:
greet("Evelyn")

Hello Evelyn
How are you?


**Repaso de matrices**

In [9]:
A=[[1,2,3],[4,5,6],[7,8,9]]
print(A)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [14]:
for fila in A:       #inprimir fila por fila
    print(fila)

[1, 2, 3]
[4, 5, 6]
[7, 8, 9]


In [15]:
for fila in A:
    print(" ".join(map(str,fila)))

1 2 3
4 5 6
7 8 9


In [17]:
import numpy as np       #Me permite hacer operaciones matemáticas

In [25]:
A=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
B=np.array([[7,8,9], [1,2,3], [0, -1, -3]])
print(B)

[[ 7  8  9]
 [ 1  2  3]
 [ 0 -1 -3]]


In [27]:
C=A+B
print(C)

[[ 8 10 12]
 [ 5  7  9]
 [ 7  7  6]]


In [28]:
P=A@B          #@ se usa para multiplicar matrices
print(P)

[[ 9  9  6]
 [33 36 33]
 [57 63 60]]


In [22]:
D=A-B
print(D)

[[-6 -6 -6]
 [ 3  3  3]
 [ 7  9 12]]


In [29]:
print(1/2*A)      #Multiplicar 1/2 elemento a elemento

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


Rango de una matriz

In [30]:
E=np.array([[1,2,3],[2,4,6],[1,1,1]])
print(E)

[[1 2 3]
 [2 4 6]
 [1 1 1]]


In [31]:
np.linalg.matrix_rank(E)

np.int64(2)

Inversa de una matriz

In [34]:
A=np.array([[1,2],[3,4]])
A_inv=np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


Transpuesta de una matriz

In [35]:
A=np.array([[1,2,3],[4,5,6]])
A_T=A.T
print(A_T)

[[1 4]
 [2 5]
 [3 6]]


Matriz identidad

In [36]:
I=np.identity(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
I=np.identity(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


¿Cómo defino un vector?

In [38]:
v=np.array([1,2,3])
print(v)

[1 2 3]


In [40]:
np.linalg.norm(v)       #Norma euclideana

np.float64(3.7416573867739413)

In [42]:
np.sqrt(14)

np.float64(3.7416573867739413)

In [43]:
np.linalg.norm(v, ord=1) 

np.float64(6.0)

In [44]:
np.linalg.norm(v, ord=np.inf) 

np.float64(3.0)

Resolver un sistema de ecuaciones

In [45]:
A=np.array([[3,1],[1,2]])
b=np.array([5,5])
print(A)
print(b)

[[3 1]
 [1 2]]
[5 5]


In [47]:
x=np.linalg.solve(A,b)
print(x)

[1. 2.]
