In [3]:
import numpy as np 
# Pivoteo parcial
A = #COLOCAR LA MATRIZ DE WILKINSON n=5
n = len(A)                                   # Tamaño de la matriz
L = np.eye(n)                                # Matriz triangular inferior
U = A.copy()                                 # Copia de A donde se construye U
P = np.eye(n)                                # Matriz de permutacion

#COMPLETAR EN CLASE
#______________________________________________
#______________________________________________

for k in range(n-1):                         # Recorre las columnas pivote
    p = np.argmax(abs(U[k:n, k])) + k        # Busca la fila con mayor pivote absoluto

    if p != k:                               # Si la mejor fila no es la actual
        U[[k, p], :] = U[[p, k], :]          # Intercambia filas en U
        P[[k, p], :] = P[[p, k], :]          # Intercambia filas en P

        if k > 0:                            # Si ya hay multiplicadores guardados
            L[[k, p], :k] = L[[p, k], :k]    # Intercambia la parte previa de L

    for i in range(k+1, n):                  # Recorre filas debajo del pivote
        L[i, k] = U[i, k] / U[k, k]          # Calcula el multiplicador
        U[i, :] = U[i, :] - L[i, k]*U[k, :]  # Elimina el elemento debajo del pivote

#COMPLETAR EN CLASE
#______________________________________________
#______________________________________________

rho = max_crecimiento / max_inicial          # Factor de crecimiento

print("Matriz P:")
print(P)

print("\nMatriz L:")
print(L)

print("\nMatriz U:")
print(U)

print("\nVerificacion P A:")
print(P @ A)

print("\nVerificacion L U:")
print(L @ U)

print("\nFactor de crecimiento rho:")
print(rho)

Matriz P:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Matriz L:
[[ 1.  0.  0.  0.  0.]
 [-1.  1.  0.  0.  0.]
 [-1. -1.  1.  0.  0.]
 [-1. -1. -1.  1.  0.]
 [-1. -1. -1. -1.  1.]]

Matriz U:
[[ 1.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  2.]
 [ 0.  0.  1.  0.  4.]
 [ 0.  0.  0.  1.  8.]
 [ 0.  0.  0.  0. 16.]]

Verificacion P A:
[[ 1.  0.  0.  0.  1.]
 [-1.  1.  0.  0.  1.]
 [-1. -1.  1.  0.  1.]
 [-1. -1. -1.  1.  1.]
 [-1. -1. -1. -1.  1.]]

Verificacion L U:
[[ 1.  0.  0.  0.  1.]
 [-1.  1.  0.  0.  1.]
 [-1. -1.  1.  0.  1.]
 [-1. -1. -1.  1.  1.]
 [-1. -1. -1. -1.  1.]]

Factor de crecimiento rho:
16.0
