Practica Semana 05

In [27]:
import numpy as np

In [28]:
A=np.array([[1,2,2],
           [1/2,2,0],
           [0,-2,-3]], dtype=float)
b=np.array([1,0,0], dtype=float)
n=len(A)
L=np.eye(n)
U=A.copy()                               #Copia A en U para transformarla

In [29]:
for k in range(n-1):                          #Recorre las columnas pivote
    for i in range(k+1,n):               #Recorrer las filas debajo del pivote
        L[i,k]=U[i,k]/U[k,k]             #Calcular el multiplicador L_ik
        U[i,:]=U[i,:]-L[i,k]*U[k,:]      #Eliminar el elemento debajo del pivote

In [30]:
print("Matriz L:")
print(L)

Matriz L:
[[ 1.   0.   0. ]
 [ 0.5  1.   0. ]
 [ 0.  -2.   1. ]]


In [31]:
print("\nMatriz U:")
print(U)


Matriz U:
[[ 1.  2.  2.]
 [ 0.  1. -1.]
 [ 0.  0. -5.]]


In [32]:
print("\VerificaciónA=LU:")
print(L@U)

\VerificaciónA=LU:
[[ 1.   2.   2. ]
 [ 0.5  2.   0. ]
 [ 0.  -2.  -3. ]]


In [33]:
y=np.linalg.solve(L,b)                    #Resuelve Ly=b por sustitución hacia adelante 
x=np.linalg.solve(U,y)                    #Resuelve Ux=y por sustitución hacia atras

In [34]:
print("\nSolución:")
print(x)


Solución:
[ 1.2 -0.3  0.2]


In [35]:
# Pivoteo parcial
A=np.array([[1,-6,-1],
           [2,1,0],
           [4,8,8]], dtype=float)
n=len(A)
L=np.eye(n)
U=A.copy() 
P=np.eye(n)

In [36]:
for k in range(n-1):
    p=np.argmax(abs(U[k:n,k]))+k                  #Busca la fila con mayor pivote absoluto

    if p!=k:                                      #Si la mejor fila no es la actual
        U[[k,p],:]=U[[p,k],:]                     #Intercambia filas en U
        P[[k,p],:]=P[[p,k],:]                     #Intercambia filas en P

#Aquí estaba el error: Era un error porque al hacer pivoteo parcial cambian las filas, 
#entonces también debes cambiar en L los números que ya habías guardado debajo de la diagonal
#para que coincidan con el nuevo orden de filas
#----------------------------------------------------------------------------------------
        if k>0:
            L[[k,p],:k]=L[[p,k],:k]               #Intercambio solo la parte previa de L
#-----------------------------------------------------------------------------------------

    for i in range(k+1,n):
            L[i,k]=U[i,k]/U[k,k]             #Calcular el multiplicador L_ik
            U[i,:]=U[i,:]-L[i,k]*U[k,:]      #Eliminar el elemento debajo del pivote            
    

In [37]:
print("P=")
print(P)

P=
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [38]:
print("\nL=")
print(L)


L=
[[1.    0.    0.   ]
 [0.25  1.    0.   ]
 [0.5   0.375 1.   ]]


In [39]:
print("\nU=")
print(U)


U=
[[ 4.     8.     8.   ]
 [ 0.    -8.    -3.   ]
 [ 0.     0.    -2.875]]
